export const DemoProducts=[
    {
  productId: "cow1",
  name: "RA-201",
  category: "Cow",
  price: 0.00,
  description: "Deshi fresh cow",
  productImage: "https://drive.google.com/file/d/1pMzSGeuN5vXwKoYJy7gwOBsrBzhkT3Ca/view?usp=drive_link",
  inStock: true,
    },
    {
      productId: "cow2",
      name: "RA-202",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1JVAsEupNB1DLht0ZQwBfgtRYnaL2nISU/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow3",
      name: "RA-203",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow4",
      name: "RA-204",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow5",
      name: "RA-205",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow6",
      name: "RA-206",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow7",
      name: "RA-207",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow8",
      name: "RA-208",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },  
    {
      productId: "cow9",
      name: "RA-209",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow10",
      name: "RA-210",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow11",
      name: "RA-211",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow12",
      name: "RA-212",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow13",
      name: "RA-213",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
    {
      productId: "cow14",
      name: "RA-214",
      category: "Cow",
      price: 0.00,
      description: "Deshi fresh cow",
      productImage: "https://drive.google.com/file/d/1wgh_U4rvi9uqcTXo7LFU8pPDUIw5k26f/view?usp=drive_link",
      inStock: true,
    },
  
  ]
  